### PR TITLE
Use local action in tests

### PR DESCRIPTION
**Pull request by wesleytodd**
Instead of this action pointing back to the template repo, it should probably use the local version in it's own test workflow.

I also added push to master for this, I am pretty sure it is what most people will expect.  I can break that out into a separate PR if you all think it is necessary.

EDIT: looks like my editor also removed trailing whitespace 🤷‍♂

### CODE REVIEW

**Comment by wesleytodd** [comment]
And since I was expecting this to run on the PR and it didn't I also went ahead and added run on PR's.  Again, I can move this to a separate PR if you want.

**Comment by bryanmacfarlane** [comment]
Changing to local looks like a good change.  However, we shouldn't add master to the branch list as it does not have prod modules checked in per the walk through steps.

**Comment by wesleytodd** [comment]
I thought since it is local it still works?  I am happy to remove though as you are the expert!

**Comment by wesleytodd** [comment]
Sorry, I hit comment and should have written a bit more.

So in my mind, adding `master` here means that the tests will be run when a push happens directly on master.  So it depends on how you manage your project, but when I am the only one committing to a project I will often push on master.  In those projects, wouldn't a setup without this not run the tests?

**Comment by bryanmacfarlane** [comment]
Doh!  You're right.  Didn't have enough coffee before replying ;)

**Comment by bryanmacfarlane** [comment]
One other note on workflow - what I was doing on some of my actions was changing code in master, running all unit tests etc. and then cherry picking to releases/v1.  Then after it was green and I validated E2E, I move/add the v1 tag.  However, you are correct that getting more coverage in master is a good thing.  Thanks for your contribution!

**Comment by wesleytodd** [comment]
> One other note on workflow - what I was doing on some of my actions was changing code in master, running all unit tests etc. and then cherry picking to releases/v1. Then after it was green and I validated E2E, I move/add the v1 tag. However, you are correct that getting more coverage in master is a good thing.

I think this is a great workflow, will steal that and maybe see if there is a way to incorporate it into ci.

**Pull request merged**
