### PR TITLE
Remove extra word from the README

### PR DESCRIPTION
**Pull request by VitorNoVictor**
Hey everyone 👋 

Here's a tiny PR that removes the word `contains` from the README. The other option would be to refrase the sentence as `The action.yml contains and defines...`. 

Let me know your thoughts!

Thank you so much for your work 🙇

### CODE REVIEW

**Comment by Gowee** [comment]
(Please ignore the above incorrect mention in another project, where I put this PR's link by mistake. I have now fixed that.)

**Comment by VitorNoVictor** [comment]
No worries @Gowee 😄

**Comment by VitorNoVictor** [comment]
FYI @bryanmacfarlane @hross 👋

**Review by hross — APPROVED** [review]

**Comment by VitorNoVictor** [comment]
Thanks for the review, @hross 🙌 I have no write access to this repo, so I need your help to merge the PR 🙏

**Pull request merged**
