### PR TITLE
Fix formatting, whitespace, markdownlint, typos

### PR DESCRIPTION
**Pull request by friederbluemle**
A bunch of formatting, whitespace, markdownlint, and typo fixes.

No functional changes in this PR.

### CODE REVIEW

**Comment by friederbluemle** [comment]
Rebased onto latest master branch.

**Comment by friederbluemle** [comment]
Rebased with conflict resolved.

**Comment by hross** [comment]
this is a very old PR. if you want to fix it up I can have another look and merge it if you still want to submit it.

**Comment by friederbluemle** [comment]
@hross Thanks for the reminder! Resolved conflicts and rebased.

**Pull request merged**
